
version: 2

models:
    - name: bh_fact
      description: "Bikes hires model "
      columns:
          - name: rental_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: bh_core_agg
      description: "Aggregated tables with measures"
      columns:
        - name: year
          description: "aggregated year of measure"
          tests:
            - not_null




sources:
    - name: staging
      #For bigquery:
      database: zoomcamp-olvol3
      schema: br_staged

      # loaded_at_field: record_loaded_at
      tables:
        - name: trips_export
        - name: dim_geospatial

