
version: 2

models:
    - name: bh_fact
      description: "Bikes hires model "
      columns:
          - name: rental_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: bh_with_boroughs
      description: "Bikes hires model with boroughs dimension"
      columns:
        - name: rental_id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null




sources:
    - name: staging
      #For bigquery:
      database: zoomcamp-olvol3
      schema: br_staged

      # loaded_at_field: record_loaded_at
      tables:
        - name: br_trips

